<?php
function csas_il_theme_registry_alter(&$theme_registry) {
  $m_path = drupal_get_path('module', 'csas_il');
  $theme_registry['image']['theme path'] = $m_path;
  $theme_registry['image']['function'] = 'theme_csas_il_image';
}

function _csas_il_use_empty_img($vars = array()) {
  $use = TRUE;
  if (strpos($vars['path'], '/image_captcha') !== FALSE) {
    $use = FALSE;
  }
  elseif (!variable_get('csas_il_view_emplty_all', FALSE) || strpos($vars['path'], '/logo.')) {
    $use = FALSE;
  }
  return $use;
}

function _csas_il_use_load_img($vars = array(), $attributes = array()) {
  $use = TRUE;

  if (strpos($vars['path'], '/image_captcha') !== FALSE) {
    $use = FALSE;

  }
  elseif (!empty($attributes['class']) && in_array('csas-no-image-load', $attributes['class'], TRUE)) {
    $use = FALSE;
  }
  return $use;
}

function theme_csas_il_image($variables) {

  if (_csas_il_use_empty_img($variables)) {
    $attributes = $variables['attributes'];
    $attributes['src'] = '/' . drupal_get_path('module', 'csas_il') . '/images/empty.jpg';
  }
  else {
    static $csas_il_counter;
    if (!isset($csas_il_counter)) {
      $csas_il_counter = 0;
    }
    $csas_il_counter++;
    $attributes = $variables['attributes'];
    $attributes['src'] = file_create_url($variables['path']);
    $use_load = _csas_il_use_load_img($variables, $attributes);
    $src = _csas_il_build_src($attributes);
    $par_url = parse_url(url('', array('absolute' => TRUE)));

    if (!empty($par_url['host'])) {
      $bas_url = 'http://' . $par_url['host'];
      if (strpos($src, $bas_url) === 0) {
        $src = str_replace($bas_url, '', $src);
      }
    }

    if ($use_load
      && $csas_il_counter > variable_get('csas_il_load_count', 15)
    ) {
      if (empty($attributes['class']) || !in_array('owl-lazy', $attributes['class'], TRUE)) {
        $attributes['data-src'] = $src;
        $attributes['src'] = '/' . drupal_get_path('module', 'csas_il') . '/images/transparent.gif';

        if (isset($attributes['class'])) {
          $attributes['class'][] = ' csas-il';
        }
        else {
          $attributes['class'][] = 'csas-il';
        }
      }
    }
    else {
      $attributes['src'] = $src;
    }
  }

  foreach (array('width', 'height', 'alt', 'title') as $key) {
    if (isset($variables[$key])) {
      $attributes[$key] = $variables[$key];
    }
  }

  return '<img' . drupal_attributes($attributes) . ' />';
}

function _csas_il_build_src($attributes) {
  global $language;

  $exist_file_path = $attributes['src'];
  $abs_url = url('/', array('absolute' => TRUE));
  $abs_url_ex = explode('/', $abs_url);
  $abs_url_ex = array_slice($abs_url_ex, 0, 3);
  $abs_url = implode('/', $abs_url_ex);

  // url && external
  if (strpos($exist_file_path, 'http') !== FALSE && strpos($exist_file_path, $abs_url) === 0) {
    $parse_url = parse_url($exist_file_path);
    if (!empty($parse_url['path'])) {
      $exist_file_path = $parse_url['path'];
    }
  }
  if (substr($exist_file_path, 0, 1) === '/') {
    $exist_file_path = substr($exist_file_path, 1);
  }

  //get original path for image with style
  if (strpos($exist_file_path, url('/', array('absolute' => TRUE))) === 0 || strpos($exist_file_path, 'http') !== 0) {
    $parse_url = parse_url($exist_file_path);
    if (!empty($parse_url['path'])) {
      $path_ex = explode('public', $parse_url['path']);
      if (!empty($path_ex) && count($path_ex) == 2) {
        $exist_file_path = 'public://' . $path_ex[1];
      }
    }
  }

  if (!file_exists($exist_file_path)) {
    $src = '/' . drupal_get_path('module', 'csas_il') . '/images/empty.jpg';
  }
  else {
    $src = $attributes['src'];
  }
  return $src;
}

function csas_il_init() {
  $m_path = drupal_get_path('module', 'csas_il');
  drupal_add_js($m_path . '/csas_il.js');
  $js_set = array(
    'csas_il' => array(
      'useVis' => variable_get('csas_il_use_visible', FALSE) ? 1 : 0,
      'inScr' => variable_get('csas_il_only_in_scr_are', TRUE) ? 1 : 0,
    )
  );
  drupal_add_js($js_set, 'setting');
  drupal_add_css($m_path . '/csas_il.css');
}

/**
 * Implementation of hook_menu().
 */
function csas_il_menu() {
  $items['admin/config/content/csas_il'] = array(
    'title' => 'Csas image load',
    'description' => 'Csas image load',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('csas_il_admin_config_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'csas_il.admin.inc',
  );
  return $items;
}